### ISSUE TITLE
publish official release to maven central

### ISSUE THREAD

**Issue by christian-draeger** [HtmlUnit/htmlunit-android#1]
@rbri i am not able to find  htmlunit-android in sonatype releases repository (maven central)
![image](https://user-images.githubusercontent.com/22223458/154820722-32407e46-1cd5-4cb4-9953-4cdee4c8fd97.png)

it seems its just available as a snapshot release for now
![image](https://user-images.githubusercontent.com/22223458/154820775-a076dfe7-5891-4e87-8668-bfbfe62780d0.png)

motivation: since snapshot releases implementation can change at any time i hope you can understand that i dont want to add a snapshot release as a dependency to my project, because of stability and security reasons.

- **could you please do an "official release"?** 
- **Will the android release (since it's technically the same as the "real" htmlunit) have the same release cycle as htmlunit?**

**Comment by rbri** [comment]
Release is there and also a first snapshot build for 2.59.0-SNAPSHOT.
The snapshot points to the latest HtmlUnit snapshot that already has the fix for the clipboard handling generating an exception on android.

**Comment by rbri** [comment]
Thanks for testing and all the feedback.
