### ISSUE TITLE
Version 2.67.0 not available on mvnrepository.com

### ISSUE THREAD

**Issue by MarufRien1** [HtmlUnit/htmlunit-android#11]
As of now 2.67.0 is not available on mvnrepository.com 

![Screenshot_20221127-051857](https://user-images.githubusercontent.com/74663078/204112299-9d1d782a-a4ed-448f-ae6a-7019b4c18397.png)

**Comment by MarufRien1** [comment]
for that cant use 2.67.0 on gradle

**Comment by rbri** [comment]
strange - seems like something was going wrong during the release. Have deployed again - hope it will be available soon.
