### ISSUE TITLE
Any date for the v2.70.0 port ?

### ISSUE THREAD

**Issue by RobbWatershed** [HtmlUnit/htmlunit-android#18]

**Comment by rbri** [comment]
I like to skip the 2.70 - the next version will be the 3.0.0.

The new version will be in sync with HtmlUnit 3.0.0 - see https://www.htmlunit.org/migration.html

It will be great if you can test the lastest snapshot - you need this 

    <dependency>
        <groupId>org.htmlunit</groupId>
        <artifactId>htmlunit-android</artifactId>
        <version>3.0.0-SNAPSHOT</version>
    </dependency>

and this new snapshot repo

    <repository>
      <id>OSS Sonatype snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
      </snapshots>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>

**Comment by rbri** [comment]
Sorry for the long wait - but there was a lot of things to do to make this finally happen.

3.1.0 is out! Enjoy and report your findings.
