### ISSUE TITLE
Error in Build with 2.59.0 SNAPSHOT: netscape\javascript\package-info;' cannot be represented in dex format

### ISSUE THREAD

**Issue by sengsational** [HtmlUnit/htmlunit-android#2]
build.grade:
```
    dependencies {
        implementation 'net.sourceforge.htmlunit:htmlunit-android:2.59.0-SNAPSHOT'
        ...
    }
```
Error found under jetified-htmlunit-android-2.59.0-SNAPSHOT.jar: 
```
    com.android.tools.r8.internal.r8: Class descriptor 'Lnetscape\javascript\package-info;' cannot be represented in dex format.
```

Running gradlew -q app:dependencies --configuration releaseRuntimeClasspath:

```
+--- net.sourceforge.htmlunit:htmlunit-android:2.59.0-SNAPSHOT
|    +--- xalan:xalan:2.7.2
|    |    \--- xalan:serializer:2.7.2
|    +--- org.apache.commons:commons-lang3:3.12.0
|    +--- org.apache.commons:commons-text:1.9
|    +--- commons-io:commons-io:2.10.0
|    +--- commons-logging:commons-logging:1.2
|    +--- commons-net:commons-net:3.8.0
|    +--- commons-codec:commons-codec:1.15
|    +--- org.brotli:dec:0.1.2
|    +--- com.shapesecurity:salvation2:3.0.0
|    \--- org.eclipse.jetty.websocket:websocket-client:9.4.45.v20220203
|         +--- org.eclipse.jetty:jetty-client:9.4.45.v20220203
|         |    +--- org.eclipse.jetty:jetty-http:9.4.45.v20220203
|         |    |    +--- org.eclipse.jetty:jetty-util:9.4.45.v20220203
|         |    |    \--- org.eclipse.jetty:jetty-io:9.4.45.v20220203
|         |    |         \--- org.eclipse.jetty:jetty-util:9.4.45.v20220203
|         |    \--- org.eclipse.jetty:jetty-io:9.4.45.v20220203 (*)
|         +--- org.eclipse.jetty:jetty-util:9.4.45.v20220203
|         +--- org.eclipse.jetty:jetty-io:9.4.45.v20220203 (*)
|         \--- org.eclipse.jetty.websocket:websocket-common:9.4.45.v20220203
|              +--- org.eclipse.jetty.websocket:websocket-api:9.4.45.v20220203
|              +--- org.eclipse.jetty:jetty-util:9.4.45.v20220203
|              \--- org.eclipse.jetty:jetty-io:9.4.45.v20220203 (*)
```

Earlier package-info issue: https://github.com/HtmlUnit/htmlunit/issues/133#issuecomment-1053674599

**Comment by lqh995204185** [comment]
@sengsational 
I directly download the jar package and import it

implementation files('libs/htmlunit-android-2.59.0.jar')

I also encountered this problem. How can I solve it

**Comment by lqh995204185** [comment]
@sengsational 
delete:
/javascript/package-info
/netscape/javascript/package-info

Now it has worked for me in Android studio
But I'm not sure if it works in practice

**Comment by zerorooot** [comment]
I try to add some content in [pom.xml](https://github.com/HtmlUnit/htmlunit-android/blob/main/pom.xml) file

```xml
<exclude>netscape/package-info.class</exclude>
<exclude>netscape/javascript/package-info.class</exclude>
```

and **delete lines 61~63**

```
<exclude>commons-codec:commons-codec</exclude>
<exclude>commons-io:*</exclude>
<exclude>commons-logging:*</exclude>
```

Finally,  add in **Android studio**

```
implementation files('libs/htmlunit-android-2.59.0.jar')
implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.12.0'
```

Now it has worked for me in Android studio

**Comment by sengsational** [comment]
@zerorooot @lqh995204185 Thank you for the suggestions.  I am unable to make progress.  I am afraid that because I do not have proper context to know where and how to make the suggested changes, I am getting a `Transform's input file does not exist` error.  Please advise me what I'm doing wrong and more detailed steps for me to make these changes.

Here are the steps I executed:

1) Locate `htmlunit-android-2.59.0.jar` (found in `C:\Users\Owner\.gradle\caches\modules-2\files-2.1\net.sourceforge.htmlunit\htmlunit-android\2.59.0-SNAPSHOT\ed7b1a0371f6a0184a2cc63552086f0245295531\htmlunit-android-2.59.0.jar`)

2) Rename  `htmlunit-android-2.59.0.jar` to  `htmlunit-android-2.59.0.zip`

3) Extract  `htmlunit-android-2.59.0.zip` to `tmp`

4) Edit 'tmp\htmlunit-android-2.59.0-SNAPSHOT\META-INF\maven\net.sourceforge.htmlunit\htmlunit-android\pom.xml'

Resulting in: 

>  <x>
    <build>
    <plugins>
    ....
      <plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
    ....
            </goals>
            <configuration>
              <artifactSet>
                <excludes>
                  <exclude>org.apache.commons:*</exclude>
                  <exclude>commons-net:*</exclude>
                  <exclude>org.brotli:*</exclude>
                  <exclude>com.shapesecurity:*</exclude>
                  <exclude>xalan:*</exclude>
                  <exclude>org.eclipse.jetty.websocket:*</exclude>
                  <exclude>org.eclipse.jetty:*</exclude>
                  <exclude>netscape/package-info.class</exclude>
                  <exclude>netscape/javascript/package-info.class</exclude>
                </excludes>

5) Zip `htmlunit-android-2.59.0.zip` and rename to `htmlunit-android-2.59.0.jar` 

6) Place the `htmlunit-android-2.59.0.jar` file in `C:\Users\Owner\AndroidStudioProjects\MyApplication2\app\libs\` folder.

7) Edit build.gradle:

>  <x>
     dependencies {

        //implementation 'net.sourceforge.htmlunit:htmlunit-android:2.59.0-SNAPSHOT' (removed)  
        implementation files('libs/htmlunit-android-2.59.0.jar')
        implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.12.0'

**RESULTING ERROR:**

Transform's input file does not exist: C:\Users\Owner\AndroidStudioProjects\MyApplication2\app\libs\htmlunit-android-2.59.0.jar. (See https://issuetracker.google.com/issues/158753935)

**Comment by zerorooot** [comment]
> @zerorooot @lqh995204185 Thank you for the suggestions. I am unable to make progress. I am afraid that because I do not have proper context to know where and how to make the suggested changes, I am getting a `Transform's input file does not exist` error. Please advise me what I'm doing wrong and more detailed steps for me to make these changes.
> 
> Here are the steps I executed:
> 
> 1. Locate `htmlunit-android-2.59.0.jar` (found in `C:\Users\Owner\.gradle\caches\modules-2\files-2.1\net.sourceforge.htmlunit\htmlunit-android\2.59.0-SNAPSHOT\ed7b1a0371f6a0184a2cc63552086f0245295531\htmlunit-android-2.59.0.jar`)
> 2. Rename  `htmlunit-android-2.59.0.jar` to  `htmlunit-android-2.59.0.zip`
> 3. Extract  `htmlunit-android-2.59.0.zip` to `tmp`
> 4. Edit 'tmp\htmlunit-android-2.59.0-SNAPSHOT\META-INF\maven\net.sourceforge.htmlunit\htmlunit-android\pom.xml'
> 
> Resulting in:
> 
> > 
> 
> ```
> <build>
> <plugins>
> ....
>   <plugin>
>     <artifactId>maven-shade-plugin</artifactId>
>     <executions>
>       <execution>
> ....
>         </goals>
>         <configuration>
>           <artifactSet>
>             <excludes>
>               <exclude>org.apache.commons:*</exclude>
>               <exclude>commons-net:*</exclude>
>               <exclude>org.brotli:*</exclude>
>               <exclude>com.shapesecurity:*</exclude>
>               <exclude>xalan:*</exclude>
>               <exclude>org.eclipse.jetty.websocket:*</exclude>
>               <exclude>org.eclipse.jetty:*</exclude>
>               <exclude>netscape/package-info.class</exclude>
>               <exclude>netscape/javascript/package-info.class</exclude>
>             </excludes>
> ```
> 
> 5. Zip `htmlunit-android-2.59.0.zip` and rename to `htmlunit-android-2.59.0.jar`
> 6. Place the `htmlunit-android-2.59.0.jar` file in `C:\Users\Owner\AndroidStudioProjects\MyApplication2\app\libs\` folder.
> 7. Edit build.gradle:
> 
> > 
> 
> ```
>  dependencies {
> 
>     //implementation 'net.sourceforge.htmlunit:htmlunit-android:2.59.0-SNAPSHOT' (removed)  
>     implementation files('libs/htmlunit-android-2.59.0.jar')
>     implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.12.0'
> ```
> 
> **RESULTING ERROR:**
> 
> Transform's input file does not exist: C:\Users\Owner\AndroidStudioProjects\MyApplication2\app\libs\htmlunit-android-2.59.0.jar. (See https://issuetracker.google.com/issues/158753935)

It needs to be recompiled according to the source code

**Comment by sengsational** [comment]
>there is an updated version of the compiler plugin, the latest snapshot (2.60.0-SNAPSHOT) is build using the fixed version. Please try and check if the problem is gone.

This version has resolved my problem.

Specifically, to `build.gradle (:app)`, I simply added:

    dependencies {
        implementation 'net.sourceforge.htmlunit:htmlunit-android:2.60.0-SNAPSHOT'
        ....

The above requires that `settings.gradle (applicationName)` include:

    dependencyResolutionManagement {
        repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
        repositories {
            ....
            maven { url 'https://oss.sonatype.org/content/repositories/snapshots'}
            ....

**Comment by zerorooot** [comment]
@rbri 
When I exclude the package-info.class file, after importing and compiling, report errors

```
java.lang.NoClassDefFoundError
```

So i removed it.

**Comment by rbri** [comment]
@zerorooot can you please check with the latest snapshot build
And if you still het this classnotfound exception please include the name of the class from the exception

**Comment by zerorooot** [comment]
@rbri 
Everything works fine with the latest  snapshot build, thank you very much

**Comment by rbri** [comment]
@zerorooot a release is planned for this weekend.
Thanks for the feedback.
