### ISSUE TITLE
JS Timer functions are not working with `executeJavaScript()`

### ISSUE THREAD

**Issue by MohRaouf** [HtmlUnit/htmlunit-android#48]
## Issue
Setting alert handler that should be asynchronously handling `alert()` that exists in `setInterval`  in the script, 
it doesn't work, however when execute the script without `setInterval` it works,
```
 try (WebClient webClient = new WebClient()) {
                    webClient.getOptions().setJavaScriptEnabled(true);
                    webClient.getOptions().setUseInsecureSSL(true);
                    webClient.setCssErrorHandler(new SilentCssErrorHandler());
                    webClient.setAlertHandler((AlertHandler) (page, s) -> runOnUiThread(() -> {
                        Toast.makeText(MainActivity.this, "There's some thing here", Toast.LENGTH_SHORT).show();
                    }));
                    final HtmlPage page = webClient.getPage("https://192.168.1.254");
                    String script = """
                            setInterval(() => {
                                alert('setInterval ended')
                            }, 1000);
                            """;
                    page.executeJavaScript(script);

                } catch (IOException e) {
                    // Handle the exception on the UI thread
                    runOnUiThread(() -> {
                        Toast.makeText(MainActivity.this, "Error fetching web page: " + e.getMessage(), Toast.LENGTH_SHORT).show();
                    });
                }
```

## Help
Please advise if there's another better way to achieve the same behavior (call Java method from the JS script)

**Comment by MohRaouf** [comment]
Update: Timer functions work by adding the following snippet after `executeJavaScript(script)` 

```
                   do {
                        webClient.waitForBackgroundJavaScript(1000); // Adjust timeout as needed
                    } while (true);
```
However I'll leave it open for any suggestions on better way to achieve the same behavior (call Java method from the JS script)

**Comment by rbri** [comment]
@MohRaouf that is the expected behaviour - the js stuff runs in a separate thread - and therefore webClient.getPage() does NOT wait for the timer to complete.

page.executeJavaScript(script); is synchronous and waits for the result; but in your case the setInterval is executed and then the js function returns.

This is one use case for the waitForBackgroundJavaScript() method.

Hope that helps.... & thanks for using HtmlUnit.

**Comment by MohRaouf** [comment]
Hi @rbri,

Thanks for your previous explanation! It was very helpful.

**My Use Case:**

I have JS code running inside a setInterval that needs to send messages back to the Java thread.

**Current Approach:**

To achieve this, I'm using alert in the JS code. When a message needs to be sent, an alert is triggered with the message content.
In Java, I handle these alerts using AlertHandler.

**Question:**

While this works, I'm curious if you (as an expert) have any suggestions for more efficient ways to achieve the same functionality.
