### ISSUE TITLE
android studio build duplicate file error

### ISSUE THREAD

**Issue by saed220** [HtmlUnit/htmlunit-android#49]
in kts file i import the htmlUnit like this :implementation( group = "org.htmlunit", name = "htmlunit3-android", version = "3.7.0") and whenever i try to run the code i get this error:"org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
java.lang.RuntimeException: Duplicate class netscape.javascript.JSException found in modules htmlunit-android-2.63.0 (net.sourceforge.htmlunit:htmlunit-android:2.63.0) and htmlunit3-android-3.7.0 (org.htmlunit:htmlunit3-android:3.7.0)
org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
com.android.builder.merge.DuplicateRelativeFileException: 2 files found with path 'org/htmlunit/org/apache/commons/codec/language/bm/sep_hebrew_common.txt' from inputs:
com.android.builder.merge.DuplicateRelativeFileException: 2 files found with path 'org/htmlunit/org/apache/commons/codec/language/bm/sep_hebrew_common.txt'.
Duplicate class found"   ,"Caused by: java.lang.RuntimeException: Duplicate class netscape.javascript.JSException found in modules htmlunit-android-2.63.0 (net.sourceforge.htmlunit:htmlunit-android:2.63.0) and htmlunit3-android-3.7.0 (org.htmlunit:htmlunit3-android:3.7.0)
"  ,"Caused by: com.android.builder.merge.DuplicateRelativeFileException: 2 files found with path 'org/htmlunit/org/apache/commons/codec/language/bm/sep_hebrew_common.txt' from inputs:
"  ,"Caused by: com.android.builder.merge.DuplicateRelativeFileException: 2 files found with path 'org/htmlunit/org/apache/commons/codec/language/bm/sep_hebrew_common.txt'.
" ,"Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
"

**Comment by rbri** [comment]
Looks like you have two different versions of htmlunit in your classpath. Make sure to remove the version htmlunit-android-2.63.0 .

**Comment by saed220** [comment]
yes . the problem was made by skrapit library . it uses another version of htmlUnit

**Comment by rbri** [comment]
thanks for the feedback. will close this.

Have fun/success using HtmlUnit and feel free to open new issues if you face any problems
