### ISSUE TITLE
How to change user-agent?

### ISSUE THREAD

**Issue by OpacareAngelus** [HtmlUnit/htmlunit-android#50]
I can't change user agent for this browser.
My web-service working only with mobile clients, but agent of HtmlUnit is:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
I tried to change that:
 webClient.browserVersion.userAgent = WebSettings.getDefaultUserAgent(requireContext())
But: Val cannot be reassigned
How can i change userAgent, any idea?

**Comment by rbri** [comment]
> How can i change userAgent, any idea?

Yes ;-)

Have added a small piece of sample code to the docs - https://www.htmlunit.org/webclient.html#Change_the_browser_user_agent

Hope that helps.

**Comment by OpacareAngelus** [comment]
> > How can i change userAgent, any idea?
> 
> Yes ;-)
> 
> Have added a small piece of sample code to the docs - https://www.htmlunit.org/webclient.html#Change_the_browser_user_agent
> 
> Hope that helps.

Ty :) It's helped me
