### ISSUE TITLE
java.lang.VerifyError: Verifier rejected

### ISSUE THREAD

**Issue by pangzhaiwei** [HtmlUnit/htmlunit-android#6]
hello，there is an AndroidRuntime Exception after I set minifyEnabled as true in build.gradle:

> java.lang.VerifyError: Verifier rejected class com.gargoylesoftware.htmlunit.javascript.host.file.FileReader: void com.gargoylesoftware.htmlunit.javascript.host.file.FileReader.readAsDataURL(java.lang.Object) failed to verify: void com.gargoylesoftware.htmlunit.javascript.host.file.FileReader.readAsDataURL(java.lang.Object): [0x15] 'this' argument 'Precise Reference: org.apache.commons.codec.binary.Base64' not instance of 'Reference: org.apache.commons.codec.binary.BaseNCodec' (declaration of 'com.gargoylesoftware.htmlunit.javascript.host.file.FileReader' appears in base.apk!classes2.dex)
>         at java.lang.reflect.Field.get(Native Method)
>         at com.gargoylesoftware.htmlunit.javascript.configuration.ClassConfiguration.addConstant(SourceFile:3)
>         at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.a(SourceFile:66)
>         at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.getClassConfiguration(SourceFile:51)
>         at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.a(SourceFile:3)
>         at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.<init>(SourceFile:2)
>         at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.<init>(SourceFile:1)
>         at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.getInstance(SourceFile:2)
>         at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.<init>(SourceFile:5)
>         at com.gargoylesoftware.htmlunit.WebClient.<init>(SourceFile:34)
>         at com.gargoylesoftware.htmlunit.WebClient.<init>(SourceFile:3)
>         at com.gargoylesoftware.htmlunit.WebClient.<init>(SourceFile:2)

**Comment by pangzhaiwei** [comment]
and the version of htmlunit-android which I use in my project is 2.60.0-SNAPSHOT, could anyone please help me?

**Comment by rbri** [comment]
I'm on vacation this week will have a look at this when I'm back.

**Comment by rbri** [comment]
Looks like ecluding commons-codex from shading is no good idea - fixes.

@pangzhaiwei please try 2.62.0-SNAPSHOT and report your findings

**Comment by rbri** [comment]
@pangzhaiwei sorry but i made a mistake - please use 2.6**3**.0-SNAPSHOT for testing

**Comment by pangzhaiwei** [comment]
Thank you very much, @rbri 2.63.0-SNAPSHOT works well. But it seems need to add proguard rules like below:
```
-keep class com.gargoylesoftware.** { *; }
-keep class javax.xml.** { *; }
-keep class net.sourceforge.htmlunit.** { *; }
-keep class netscape.** { *; }
-keep class org.apache.** { *; }
-keep class org.htmlunit.org.apache.** { *; }
-keep class org.w3c.dom.** { *; }
-keep class org.xml.sax.** { *; }
```
otherwise it will occur exception like below:
```
java.lang.IllegalArgumentException: Cannot locate declared field class org.htmlunit.org.apache.http.impl.client.HttpClientBuilder.publicSuffixMatcher
        at org.apache.commons.lang3.Validate.isTrue(SourceFile:3)
        at org.apache.commons.lang3.reflect.FieldUtils.readDeclaredField(SourceFile:5)
        at com.gargoylesoftware.htmlunit.HttpWebConnection.a(SourceFile:231)
        at com.gargoylesoftware.htmlunit.HttpWebConnection.b(SourceFile:22)
        at com.gargoylesoftware.htmlunit.HttpWebConnection.b(SourceFile:20)
        at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(SourceFile:1)
        at com.gargoylesoftware.htmlunit.WebClient.a(SourceFile:107)
        at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(SourceFile:2)
        at com.gargoylesoftware.htmlunit.WebClient.a(SourceFile:26)
        at com.gargoylesoftware.htmlunit.WebClient.getPage(SourceFile:1)
        at com.gargoylesoftware.htmlunit.WebClient.getPage(SourceFile:7)
```
Those proguard rules maybe not need to add all, but I think this library not need to be confused.
Thank you very much, @rbri .

**Comment by rbri** [comment]
3.1.0 is out - hopefully all these problems are solved now.

Please try and report any problems.
